[formatting]
trailing_newline = true
indent_string = "    "

# the above options agree with .editorconfig and are only specified so that
# taplo-cli can use them in CI

[[rule]]
include = ["resources/*.toml"]

[rule.schema]
path = "./resources/resource.schema.json"
enabled = true

[[rule]]
include = ["schedule/*.toml"]

[rule.schema]
path = "./schedule/week.schema.json"
enabled = true
